### ISSUE TITLE
i am trying this, but getting this error, while importing, installed rxjs also, but still the same.

### ISSUE THREAD

**Issue by tdpksingh** [devx-os/react-holmes#1]
error - ./node_modules/@devx-os/react-holmes/dist/hooks/useObservable/useObservable.js:2:0
Module not found: Can't resolve 'rxjs'

Import trace for requested module:
./node_modules/@devx-os/react-holmes/dist/hooks/useHolmesValue/useHolmesValue.js
./node_modules/@devx-os/react-holmes/dist/hooks/index.js
./node_modules/@devx-os/react-holmes/dist/index.js

**Comment by riktar** [comment]
Hi, thank you for try this.
Can you share your package.json?

Anyway, try this

```
sudo rm -rf ./package-lock.json ./node_modules

npm install
```

**Comment by tdpksingh** [comment]
tried above steps, still the same error,

here is package.json
{
  "name": "my-app",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "browser": {
    "fs": false,
    "path": false,
    "os": false,
    "crypto": false,
    "stream": false,
    "http": false,
    "tls": false,
    "zlib": false,
    "https": false,
    "net": false,
    "child_process": false
  },
  "dependencies": {
    "@chakra-ui/icons": "^1.1.7",
    "@chakra-ui/react": "^1.8.8",
    "@devx-os/react-holmes": "^0.2.0",
    "@emotion/react": "^11.9.0",
    "@emotion/styled": "^11.8.1",
    "axios": "^0.27.2",
    "axios-jwt": "^1.8.0",
    "chakra-ui-steps": "^1.7.3",
    "formik": "^2.2.9",
    "framer-motion": "^6.2.10",
    "immer": "^9.0.12",
    "next": "12.1.4",
    "react": "^18.1.0",
    "react-dom": "^18.1.0",
    "react-google-recaptcha": "^2.1.0",
    "react-helmet": "^6.1.0",
    "react-icons": "^4.4.0",
    "react-input-autosize": "^3.0.0",
    "react-webcam": "^7.0.1",
    "rxjs-compat": "^6.6.7",
    "usehooks-ts": "^2.5.3",
    "yup": "^0.32.11",
    "zustand": "^4.0.0-rc.0"
  },
  "devDependencies": {
    "eslint": "8.13.0",
    "eslint-config-next": "12.1.4"
  }
}

**Comment by riktar** [comment]
Try with `npm i rxjs`

I see that you have `rxjs-compact`
